version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: laravel_user
            DB_PASSWORD: laravel_pass
        depends_on:
            - db
        networks:
            - laravel_net

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "81:80"
        depends_on:
            - app
        networks:
            - laravel_net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: laravel_user
            PMA_PASSWORD: laravel_pass
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel_net

volumes:
    mysql_data:

networks:
    laravel_net:
        driver: bridge
