version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel_net

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "81:80"
        depends_on:
            - app
        networks:
            - laravel_net

volumes:
    mysql_data:

networks:
    laravel_net:
        driver: bridge
